<?php

class CategoriesController extends AdminController
{
 public function index(){ $this->guardAdmin(); $db=new Database(); $categories=$db->fetchAll('SELECT c.*, p.name parent_name FROM categories c LEFT JOIN categories p ON p.id=c.parent_id ORDER BY c.sort_order,c.name'); $this->view('admin/categories/index',array('categories'=>$categories)); }
 public function create(){ $this->guardAdmin(); $db=new Database(); $this->view('admin/categories/form',array('category'=>null,'parents'=>$db->fetchAll('SELECT id,name FROM categories ORDER BY name'))); }
 public function store(){ $this->postGuard();$d=Sanitizer::cleanArray($_POST);$db=new Database();$db->query('INSERT INTO categories (name,slug,description,parent_id,sort_order) VALUES (:name,:slug,:description,:parent_id,:sort_order)',array(':name'=>$d['name']??'',':slug'=>$this->slug($d['slug']??$d['name']??''),':description'=>$d['description']??null,':parent_id'=>(int)($d['parent_id']??0)?:null,':sort_order'=>(int)($d['sort_order']??0)));$id=$db->lastInsertId();$this->audit('create','category',$id,null,$d);return $this->redirect('admin/categories'); }
 public function edit($id){$this->guardAdmin();$db=new Database();$category=$db->fetch('SELECT * FROM categories WHERE id=:id',array(':id'=>(int)$id));$this->view('admin/categories/form',array('category'=>$category,'parents'=>$db->fetchAll('SELECT id,name FROM categories WHERE id<>:id ORDER BY name',array(':id'=>(int)$id))));}
 public function update($id){$this->postGuard();$d=Sanitizer::cleanArray($_POST);$db=new Database();$old=$db->fetch('SELECT * FROM categories WHERE id=:id',array(':id'=>(int)$id));$db->query('UPDATE categories SET name=:name,slug=:slug,description=:description,parent_id=:parent_id,sort_order=:sort_order WHERE id=:id',array(':name'=>$d['name']??'',':slug'=>$this->slug($d['slug']??$d['name']??''),':description'=>$d['description']??null,':parent_id'=>(int)($d['parent_id']??0)?:null,':sort_order'=>(int)($d['sort_order']??0),':id'=>(int)$id));$this->audit('update','category',$id,$old,$d);return $this->redirect('admin/categories');}
 public function delete($id){$this->postGuard();$db=new Database();$old=$db->fetch('SELECT * FROM categories WHERE id=:id',array(':id'=>(int)$id));$db->query('UPDATE articles SET category_id=NULL WHERE category_id=:id',array(':id'=>(int)$id));$db->query('DELETE FROM categories WHERE id=:id',array(':id'=>(int)$id));$this->audit('delete','category',$id,$old);return $this->redirect('admin/categories');}
 private function slug($v){$s=strtolower(trim(preg_replace('/[^\p{L}\p{N}]+/u','-',(string)$v),'-'));return $s?:'category-'.time();}
}
